# Generated by Django 5.1.7 on 2025-04-16 21:41

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator_user",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectUserPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectUsers",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("is_owner", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "permissions",
                    models.ManyToManyField(
                        through="todo.ProjectUserPermissions", to="auth.permission"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="todo.projects"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "user")},
            },
        ),
        migrations.AddField(
            model_name="projectuserpermissions",
            name="project_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="todo.projectusers"
            ),
        ),
        migrations.CreateModel(
            name="TaskAssignees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="todo.projectusers",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tasks",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "CREATED"),
                            ("PREPARING", "PREPARING"),
                            ("IN_PROGRESS", "IN_PROGRESS"),
                            ("FINISHED", "FINISHED"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("body", models.TextField(blank=True, null=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignees",
                    models.ManyToManyField(
                        through="todo.TaskAssignees", to="todo.projectusers"
                    ),
                ),
                (
                    "creator_user",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finished_user",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="finished_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="todo.projects"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="taskassignees",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="todo.tasks"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectuserpermissions",
            unique_together={("project_user", "permission")},
        ),
        migrations.AddIndex(
            model_name="tasks",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["project", "status"], name="todo_tasks_project_0784f8_btree"
            ),
        ),
        migrations.AddIndex(
            model_name="tasks",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["project", "created_at"], name="todo_tasks_project_34ded9_btree"
            ),
        ),
        migrations.AddIndex(
            model_name="tasks",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["project", "title"], name="todo_tasks_project_2df149_btree"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskassignees",
            unique_together={("project_user", "task")},
        ),
    ]
