# Generated by Django 5.1.7 on 2025-05-06 12:40
from django.contrib.auth.models import Group, Permission
from django.db import migrations


def create_default_group(apps, schema_editor):
    group, created = Group.objects.get_or_create(name="Users")

    permissions = Permission.objects.filter(
        content_type__model__in=["tasks", "taskassignees", "projectusers", "projects"],
        content_type__app_label="todo",
    )

    group.permissions.set(permissions)


def remove_default_group(apps, schema_editor):
    Group.objects.filter(name="Users").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("oauth", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(create_default_group, remove_default_group),
    ]
