# Generated by Django 5.1.7 on 2025-05-06 12:40
from django.contrib.auth.models import Group, Permission
from django.db import migrations


def create_default_group(apps, schema_editor):
    user_group, _ = Group.objects.get_or_create(name="Users")
    user_group_permissions = Permission.objects.filter(
        content_type__model__in=["tasks", "taskassignees", "projectusers", "projects"],
        content_type__app_label="todo",
    )
    user_group.permissions.set(user_group_permissions)

    project_all_group, _ = Group.objects.get_or_create(name="Project All")
    project_all_group_permissions = Permission.objects.filter(
        content_type__model__in=[
            "tasks",
            "task_assignees",
            "projectusers",
            "projectuserpermissions",
            "projectuserpermissiongroups",
        ]
    )
    project_all_group.permissions.set(project_all_group_permissions)

    project_user_group, _ = Group.objects.get_or_create(name="Project Users")
    project_user_group_permissions = Permission.objects.filter(
        content_type__model__in=["tasks", "taskassignees"],
        content_type__app_label="todo",
    )
    project_user_group.permissions.set(project_user_group_permissions)

    project_moderator_group, _ = Group.objects.get_or_create(name="Project Moderators")
    project_moderator_group_permissions = Permission.objects.filter(
        content_type__model__in=[
            "tasks",
            "taskassignees",
            "projectusers",
        ],
        content_type__app_label="todo",
    )
    project_moderator_group.permissions.set(project_moderator_group_permissions)


def remove_default_group(apps, schema_editor):
    Group.objects.filter(name="Users").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("oauth", "0001_initial"),
        ("todo", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(create_default_group, remove_default_group),
    ]
