# Generated by Django 5.1.7 on 2025-05-28 11:16
from django.contrib.auth.models import Group, Permission
from django.db import migrations

from apps.oauth.models import GroupScope


def create_root_group(apps, schema_editor):
    root_group, _ = Group.objects.get_or_create(name="Root")
    root_group_permissions = Permission.objects.all()
    root_group.save()

    root_group.permissions.set(root_group_permissions)

    root_group_scope = GroupScope(group=root_group, scope="ROOT")
    root_group_scope.save()


def remove_root_group(apps, schema_editor):
    Group.objects.get(name="Root").delete()


create_trigger_query = """
CREATE OR REPLACE FUNCTION set_root_parent_id()
RETURNS TRIGGER AS $$
DECLARE
    root_parent_id integer;
BEGIN
    IF NEW.parent_id IS NULL THEN
        SELECT ogs.id INTO root_parent_id
        FROM core.oauth_group_scope ogs
        JOIN core.auth_group ag ON ag.id = ogs.group_id
        WHERE ag.name = 'Root';

        IF root_parent_id != NEW.id THEN
            NEW.parent_id := root_parent_id;
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_set_root_parent_id
BEFORE INSERT OR UPDATE ON core.oauth_group_scope
FOR EACH ROW EXECUTE FUNCTION set_root_parent_id();
"""

drop_trigger_query = """
DROP TRIGGER trg_set_root_parent_id ON core.oauth_group_scope;
"""


create_functions_query = """
CREATE OR REPLACE FUNCTION groups_hierarchy(new_scope_id bigint, new_group_id bigint)
RETURNS TABLE(parent_group_id int, group_id int, cycle bool) AS $$
    WITH RECURSIVE groups("id", "parent_id", "group_id", "path", "level", "cycle") AS (
        SELECT new_scope_id, NULL::bigint, new_group_id, array[new_scope_id], 1, false
        UNION ALL
        SELECT ogs."id", gs."group_id", ag."id", gs."path" || ogs."id", "level" + 1, ogs."id" = ANY(gs."path")
            FROM core.oauth_group_scope ogs
            INNER JOIN core.auth_group ag ON ag."id" = ogs."group_id"
            INNER JOIN groups gs ON (gs."id" = ogs."parent_id" ) AND NOT cycle
    )
    SELECT "parent_id", "group_id", "cycle"
        FROM groups gs
        ORDER BY gs."level"
$$ LANGUAGE SQL STABLE;

CREATE OR REPLACE FUNCTION check_groups_hierarchy()
RETURNS TRIGGER AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM core.groups_hierarchy(NEW.id, NEW.group_id)
        WHERE cycle = TRUE
    ) THEN
        RAISE EXCEPTION 'Cycle detected in group hierarchy starting from group with id: %', NEW.group_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER check_groups_hierarchy
AFTER INSERT OR UPDATE ON core.oauth_group_scope
FOR EACH ROW EXECUTE FUNCTION check_groups_hierarchy();
"""

drop_functions_query = """
DROP FUNCTION core.groups_hierarchy(bigint,bigint);
DROP TRIGGER check_groups_hierarchy ON core.oauth_group_scope;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("oauth", "0001_initial"),
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_root_group, remove_root_group),
        migrations.RunSQL(create_functions_query, drop_functions_query),
        migrations.RunSQL(create_trigger_query, drop_trigger_query),
    ]
