# Generated by Django 5.1.7 on 2025-05-06 12:40
from django.apps import apps as global_apps
from django.contrib.auth.management import create_permissions
from django.contrib.auth.models import Group, Permission
from django.db import migrations
from django.db.models import Q

from apps.oauth.models import GroupScope


def ensure_permissions(apps, schema_editor):
    """
    Имитируем сигнал post_migrate, создавая права для всех приложений.
    """
    for app_config in global_apps.get_app_configs():
        create_permissions(app_config, apps=apps, verbosity=0)


def create_default_group(apps, schema_editor):
    user_group, _ = Group.objects.get_or_create(name="Users")
    user_group_permissions = Permission.objects.filter(
        content_type__model__in=[
            "projects",
            "tasks",
            "projectusers",
        ],
    )
    user_group.permissions.set(user_group_permissions)

    all_group, _ = Group.objects.get_or_create(name="All")
    all_group_permissions = Permission.objects.filter(
        content_type__model__in=[
            "projects",
            "users",
            "usergroups",
            "userpermissions",
            "tasks",
            "projectusers",
        ]
    )
    all_group.permissions.set(all_group_permissions)

    project_all_group, _ = Group.objects.get_or_create(name="Project All")
    perms_query = Q(
        content_type__model__in=[
            "tasks",
            "taskassignees",
            "projectusers",
            "projectuserpermissions",
            "projectuserpermissiongroups",
        ]
    )
    perms_query |= Q(codename__in=["change_projects", "delete_projects"])
    project_all_group_permissions = Permission.objects.filter(perms_query)
    project_all_group.permissions.set(project_all_group_permissions)

    project_user_group, _ = Group.objects.get_or_create(name="Project Users")
    project_user_group_permissions = Permission.objects.filter(
        content_type__model__in=[
            "tasks",
            "taskassignees",
        ],
        content_type__app_label="todo",
    )
    project_user_group.permissions.set(project_user_group_permissions)

    project_moderator_group, _ = Group.objects.get_or_create(name="Project Moderators")
    project_moderator_group_permissions = Permission.objects.filter(
        content_type__model__in=[
            "tasks",
            "taskassignees",
            "projectusers",
        ],
        content_type__app_label="todo",
    )
    project_moderator_group.permissions.set(project_moderator_group_permissions)

    all_group_scope = GroupScope(group=all_group, scope="GLOBAL")
    project_all_group_scope = GroupScope(group=project_all_group, scope="PROJECT")
    GroupScope.objects.bulk_create(objs=[all_group_scope, project_all_group_scope])

    project_moderators_scope = GroupScope(
        group=project_moderator_group, scope="PROJECT", parent=project_all_group_scope
    )
    project_moderators_scope.save()

    user_group_scope = GroupScope(
        group=user_group, scope="GLOBAL", parent=all_group_scope
    )
    project_user_group_scope = GroupScope(
        group=project_user_group, scope="PROJECT", parent=project_moderators_scope
    )

    GroupScope.objects.bulk_create(objs=[user_group_scope, project_user_group_scope])


def remove_default_group(apps, schema_editor):
    Group.objects.filter(
        name__in=[
            "Users",
            "All",
            "Project All",
            "Project Moderators",
            "Project Users",
        ],
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("oauth", "0002_group_hierarchy_func"),
    ]

    operations = [
        migrations.RunPython(ensure_permissions, migrations.RunPython.noop),
        migrations.RunPython(create_default_group, remove_default_group),
    ]
