"""Initial

Revision ID: 0001
Revises: 
Create Date: 2025-07-04 22:54:00.934369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bucket', sa.String(length=100), nullable=False),
    sa.Column('s3_object_key', sa.String(length=256), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket', 's3_object_key'),
    schema='files'
    )
    op.create_table('project_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id'),
    schema='files'
    )
    op.create_index(op.f('ix_files_project_files_project_id'), 'project_files', ['project_id'], unique=False, schema='files')
    op.create_table('user_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id'),
    schema='files'
    )
    op.create_index(op.f('ix_files_user_files_user_id'), 'user_files', ['user_id'], unique=False, schema='files')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_user_files_user_id'), table_name='user_files', schema='files')
    op.drop_table('user_files', schema='files')
    op.drop_index(op.f('ix_files_project_files_project_id'), table_name='project_files', schema='files')
    op.drop_table('project_files', schema='files')
    op.drop_table('files', schema='files')
    # ### end Alembic commands ###
