"""Add users table

Revision ID: 0002
Revises: 0001
Create Date: 2025-04-01 19:54:48.223423

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("email", sa.String(length=128), nullable=False),
        sa.Column("username", sa.String(length=256), nullable=False),
        sa.Column("hashed_password", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_users_created_at"),
        "users",
        ["created_at"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_users_email"), "users", ["email"], unique=True, schema="auth"
    )
    op.create_index(
        op.f("ix_auth_users_is_admin"),
        "users",
        ["is_admin"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_users_username"),
        "users",
        ["username"],
        unique=False,
        schema="auth",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_auth_users_username"), table_name="users", schema="auth")
    op.drop_index(op.f("ix_auth_users_is_admin"), table_name="users", schema="auth")
    op.drop_index(op.f("ix_auth_users_email"), table_name="users", schema="auth")
    op.drop_index(op.f("ix_auth_users_created_at"), table_name="users", schema="auth")
    op.drop_table("users", schema="auth")
    # ### end Alembic commands ###
